import type { Agent, AgentTemplate, Message, Tool, Gateway, KnowledgeFile, Automation } from './types';

// Agent Templates
export const agentTemplates: AgentTemplate[] = [
  {
    id: 'general-assistant',
    name: 'General Assistant',
    description: 'A versatile AI assistant for everyday tasks, questions, and conversations.',
    icon: 'Sparkles',
    category: 'general',
    defaultPrompt: 'You are a helpful, friendly assistant. Answer questions clearly and help with tasks efficiently.',
    suggestedTools: ['web-search', 'calculator', 'reminders'],
  },
  {
    id: 'work-assistant',
    name: 'Work Assistant',
    description: 'Focused on productivity, scheduling, and professional communication.',
    icon: 'Briefcase',
    category: 'productivity',
    defaultPrompt: 'You are a professional assistant focused on work productivity. Help with scheduling, emails, and task management.',
    suggestedTools: ['calendar', 'email', 'todos', 'notes'],
  },
  {
    id: 'researcher',
    name: 'Researcher',
    description: 'Deep research and analysis with knowledge vault integration.',
    icon: 'Search',
    category: 'research',
    defaultPrompt: 'You are a thorough researcher. Analyze information carefully and provide well-sourced insights.',
    suggestedTools: ['web-search', 'knowledge-vault', 'notes', 'citations'],
  },
  {
    id: 'creative-writer',
    name: 'Creative Writer',
    description: 'Help with writing, editing, and creative content generation.',
    icon: 'Pen',
    category: 'creative',
    defaultPrompt: 'You are a creative writing assistant. Help with drafting, editing, and brainstorming creative content.',
    suggestedTools: ['notes', 'knowledge-vault', 'grammar-check'],
  },
  {
    id: 'coder',
    name: 'Code Helper',
    description: 'Programming assistance, debugging, and code review.',
    icon: 'Code',
    category: 'technical',
    defaultPrompt: 'You are a programming assistant. Help with code, debugging, and technical questions.',
    suggestedTools: ['code-runner', 'web-search', 'documentation'],
  },
  {
    id: 'personal-coach',
    name: 'Personal Coach',
    description: 'Goal tracking, motivation, and personal development.',
    icon: 'Target',
    category: 'personal',
    defaultPrompt: 'You are a supportive personal coach. Help with goal setting, motivation, and personal growth.',
    suggestedTools: ['reminders', 'todos', 'journal'],
  },
];

// Default Agents
export const defaultAgents: Agent[] = [
  {
    id: 'main-agent',
    name: 'Atlas',
    avatar: undefined,
    description: 'Your main assistant that can help with everything and configure your DailyWerk system.',
    templateId: 'general-assistant',
    isMain: true,
    isConfidential: false,
    systemPrompt: 'You are Atlas, the main DailyWerk assistant. You help users with everyday tasks and can also help configure the DailyWerk system, manage other agents, and set up automations.',
    tools: ['web-search', 'calculator', 'reminders', 'todos', 'system-config'],
    knowledgePaths: [],
    createdAt: new Date('2024-01-01'),
    lastUsedAt: new Date(),
    status: 'online',
  },
];

// Available Tools
export const availableTools: Tool[] = [
  {
    id: 'web-search',
    name: 'Web Search',
    description: 'Search the web for information and answers.',
    icon: 'Globe',
    category: 'knowledge',
    isEnabled: true,
    usageCount: 156,
  },
  {
    id: 'calculator',
    name: 'Calculator',
    description: 'Perform mathematical calculations and conversions.',
    icon: 'Calculator',
    category: 'productivity',
    isEnabled: true,
    usageCount: 42,
  },
  {
    id: 'reminders',
    name: 'Reminders',
    description: 'Set and manage reminders for future events.',
    icon: 'Bell',
    category: 'productivity',
    isEnabled: true,
    usageCount: 89,
  },
  {
    id: 'todos',
    name: 'Todo Lists',
    description: 'Create and manage task lists.',
    icon: 'CheckSquare',
    category: 'productivity',
    isEnabled: true,
    usageCount: 234,
  },
  {
    id: 'calendar',
    name: 'Calendar',
    description: 'Access and manage calendar events.',
    icon: 'Calendar',
    category: 'integration',
    isEnabled: false,
    usageCount: 0,
  },
  {
    id: 'email',
    name: 'Email',
    description: 'Read and send emails through connected accounts.',
    icon: 'Mail',
    category: 'communication',
    isEnabled: false,
    usageCount: 0,
  },
  {
    id: 'notes',
    name: 'Notes',
    description: 'Create and manage notes in your knowledge vault.',
    icon: 'FileText',
    category: 'knowledge',
    isEnabled: true,
    usageCount: 67,
  },
  {
    id: 'knowledge-vault',
    name: 'Knowledge Vault',
    description: 'Search and reference your personal knowledge base.',
    icon: 'Database',
    category: 'knowledge',
    isEnabled: true,
    usageCount: 123,
  },
  {
    id: 'code-runner',
    name: 'Code Runner',
    description: 'Execute code snippets in various languages.',
    icon: 'Terminal',
    category: 'productivity',
    isEnabled: true,
    usageCount: 45,
  },
  {
    id: 'system-config',
    name: 'System Config',
    description: 'Configure DailyWerk settings and manage agents.',
    icon: 'Settings',
    category: 'system',
    isEnabled: true,
    usageCount: 12,
  },
  {
    id: 'grammar-check',
    name: 'Grammar Check',
    description: 'Check and improve writing quality.',
    icon: 'Pencil',
    category: 'productivity',
    isEnabled: true,
    usageCount: 78,
  },
  {
    id: 'citations',
    name: 'Citations',
    description: 'Generate and manage academic citations.',
    icon: 'Quote',
    category: 'knowledge',
    isEnabled: true,
    usageCount: 23,
  },
  {
    id: 'documentation',
    name: 'Documentation',
    description: 'Search technical documentation and APIs.',
    icon: 'Book',
    category: 'knowledge',
    isEnabled: true,
    usageCount: 56,
  },
  {
    id: 'journal',
    name: 'Journal',
    description: 'Personal journaling and reflection entries.',
    icon: 'BookOpen',
    category: 'personal',
    isEnabled: true,
    usageCount: 34,
  },
];

// Sample Messages
export const sampleMessages: Message[] = [
  {
    id: '1',
    agentId: 'main-agent',
    role: 'agent',
    content: 'Hello! I\'m Atlas, your main DailyWerk assistant. I can help you with everyday tasks, answer questions, and even configure your DailyWerk system. What would you like to do today?',
    createdAt: new Date(Date.now() - 60000),
  },
  {
    id: '2',
    agentId: 'main-agent',
    role: 'user',
    content: 'Can you help me set up a reminder for my meeting tomorrow at 2pm?',
    createdAt: new Date(Date.now() - 30000),
  },
  {
    id: '3',
    agentId: 'main-agent',
    role: 'agent',
    content: 'I\'d be happy to help you set up a reminder for your meeting tomorrow at 2pm. I\'ve created the reminder for you.\n\n**Reminder Set:**\n- Meeting tomorrow at 2:00 PM\n- You\'ll receive a notification 15 minutes before\n\nIs there anything else you\'d like me to help you with?',
    createdAt: new Date(Date.now() - 15000),
  },
];

// Gateways
export const sampleGateways: Gateway[] = [
  {
    id: 'signal-1',
    type: 'signal',
    name: 'Signal Messenger',
    status: 'disconnected',
    config: {},
  },
  {
    id: 'telegram-1',
    type: 'telegram',
    name: 'Telegram',
    status: 'disconnected',
    config: {},
  },
  {
    id: 'email-1',
    type: 'email',
    name: 'Email',
    status: 'disconnected',
    config: {},
  },
  {
    id: 'calendar-1',
    type: 'calendar',
    name: 'Calendar',
    status: 'disconnected',
    config: {},
  },
];

// Knowledge Files
export const sampleKnowledgeFiles: KnowledgeFile[] = [
  {
    path: '/notes',
    name: 'Notes',
    type: 'folder',
    lastModified: new Date('2024-03-15'),
    children: [
      {
        path: '/notes/meeting-notes.md',
        name: 'meeting-notes.md',
        type: 'file',
        lastModified: new Date('2024-03-15'),
        size: 2048,
      },
      {
        path: '/notes/project-ideas.md',
        name: 'project-ideas.md',
        type: 'file',
        lastModified: new Date('2024-03-10'),
        size: 1536,
      },
    ],
  },
  {
    path: '/research',
    name: 'Research',
    type: 'folder',
    lastModified: new Date('2024-03-12'),
    children: [
      {
        path: '/research/ai-trends.md',
        name: 'ai-trends.md',
        type: 'file',
        lastModified: new Date('2024-03-12'),
        size: 4096,
      },
    ],
  },
  {
    path: '/journal',
    name: 'Journal',
    type: 'folder',
    lastModified: new Date('2024-03-14'),
    children: [],
  },
];

// Sample Automations
export const sampleAutomations: Automation[] = [
  {
    id: 'auto-1',
    type: 'cron',
    name: 'Daily Summary',
    description: 'Get a summary of your day every evening at 6pm.',
    agentId: 'main-agent',
    schedule: '0 18 * * *',
    isEnabled: true,
    lastRun: new Date(Date.now() - 86400000),
    nextRun: new Date(Date.now() + 43200000),
  },
  {
    id: 'auto-2',
    type: 'reminder',
    name: 'Team Meeting',
    description: 'Weekly team sync meeting',
    agentId: 'main-agent',
    dueDate: new Date(Date.now() + 172800000),
    isEnabled: true,
  },
  {
    id: 'auto-3',
    type: 'todo',
    name: 'Review project proposal',
    agentId: 'main-agent',
    dueDate: new Date(Date.now() + 86400000),
    isCompleted: false,
    isEnabled: true,
  },
  {
    id: 'auto-4',
    type: 'todo',
    name: 'Send weekly report',
    agentId: 'main-agent',
    dueDate: new Date(Date.now() - 86400000),
    isCompleted: true,
    isEnabled: true,
  },
];
